// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxHZx2lOBlVRPHRxOssjSe-Nx9-UggRQ',
    appId: '1:1075270564986:web:ae26fdbfd62447e0accfc3',
    messagingSenderId: '1075270564986',
    projectId: 'easacc-task-e617d',
    authDomain: 'easacc-task-e617d.firebaseapp.com',
    storageBucket: 'easacc-task-e617d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh3nlRWTX6elQ8x8hND1s1b703t0jBfDc',
    appId: '1:1075270564986:android:9769cff51f1a3623accfc3',
    messagingSenderId: '1075270564986',
    projectId: 'easacc-task-e617d',
    storageBucket: 'easacc-task-e617d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa2Ell4E4MOt5Yw0a7iSX0OMTClikZUp4',
    appId: '1:1075270564986:ios:68bf50bf4518696baccfc3',
    messagingSenderId: '1075270564986',
    projectId: 'easacc-task-e617d',
    storageBucket: 'easacc-task-e617d.firebasestorage.app',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa2Ell4E4MOt5Yw0a7iSX0OMTClikZUp4',
    appId: '1:1075270564986:ios:68bf50bf4518696baccfc3',
    messagingSenderId: '1075270564986',
    projectId: 'easacc-task-e617d',
    storageBucket: 'easacc-task-e617d.firebasestorage.app',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxHZx2lOBlVRPHRxOssjSe-Nx9-UggRQ',
    appId: '1:1075270564986:web:ff77127ddade0789accfc3',
    messagingSenderId: '1075270564986',
    projectId: 'easacc-task-e617d',
    authDomain: 'easacc-task-e617d.firebaseapp.com',
    storageBucket: 'easacc-task-e617d.firebasestorage.app',
  );

}